version: "3.9"

services:
  app:
    build:
      context: .
      target: demo-cdk-pipeline-spring-boot
    environment:
      APP_URL: http://localhost
      MAVEN_CONFIG: /root/.m2
      SERVER_PORT: 80
      SPRING_PROFILES_ACTIVE: dev # local
    expose:
      - 80
    extra_hosts: # For Linux
      - host.docker.internal:host-gateway
    ports:
      - 80:80
    tty: true
    volumes:
      - ./:/usr/src/app
      - ${HOME}/.m2/repository:/root/.m2/repository
